/*
 *
 * ItemsList constants
 *
 */

export const ITEMS_RECEIVED_ERROR = 'ITEMS_RECEIVED_ERROR';
export const ITEMS_RECEIVED_SUCCESS = 'ITEMS_RECEIVED_SUCCESS';
export const ITEM_DELETED_SUCCESS = 'ITEM_DELETED_SUCCESS';
export const ITEM_DELETED_ERROR = 'ITEM_DELETED_ERROR';
