/*
 *
 * Dashboard constants
 *
 */
export const CATEGORIES_RECEIVED_SUCCESS = 'CATEGORIES_RECEIVED_SUCCESS';
export const CATEGORIES_RECEIVED_ERROR = 'CATEGORIES_RECEIVED_ERROR';
export const SUBCATEGORIES_RECEIVED_SUCCESS = 'SUBCATEGORIES_RECEIVED_SUCCESS';
export const SUBCATEGORIES_RECEIVED_ERROR = 'SUBCATEGORIES_RECEIVED_ERROR';
export const MERCHANTS_RECEIVED_SUCCESS = 'MERCHANTS_RECEIVED_SUCCESS';
export const MERCHANTS_RECEIVED_ERROR = 'MERCHANTS_RECEIVED_ERROR';

